### ISSUE TITLE
Moz extension in url

### ISSUE THREAD

**Issue by garaw7** [nimaaskarian/nitab#10]
Hey i migrated from other new tab extensions and like yours the most. I really enjoy the terminal, best feature by far, the only problem i have is that when you open a new tab. There is the moz extension id in the address bar, is there anyway of deleting this with css or something? thank you please i have ocd.

**Comment by nimaaskarian** [comment]
I'm glad to enjoyed the terminal! thats my favorite feature as well.
Lmao. I have OCD too, and this, drives me crazy.
Best solution that I came across is to install [one-line-firefox](https://github.com/khuedoan/one-line-firefox). this is the end result: 
![result](https://user-images.githubusercontent.com/88832088/211381532-944eb485-7636-49da-a125-b6d6a8ce6f08.png)

**Comment by garaw7** [comment]
Haha thanks, i figured using a one liner would work. New to css so i wanted to know about if there are any other methods. 

I actually was able to remove the "Extension (Nitab") tag in front of the address bar and also I used some css to remove the text from the address bar.  The css makes the text invisible, so as your typing you wont see what your typing in the address bar. It's the best workaround i could find. 

I'm mainly gonna use your terminal to navigate but I did this so the off chance i wanna go to about:config and such, I can just shortcut to the address bar and go from there.

Also last thing is there anyway i can change the color of the clock. I'm new to css lol, literally started this past week. I wanna be able to color and move the clock font and also is there a way to do the same with the terminal text? I'm muslim so I like reading from right to left, so i wanted to adjust the terminal for that perspective. Is this possible with css?

**Comment by nimaaskarian** [comment]
hey.
you can change the color of foreground using `/fg <color name or code or rgb>`, basically anything that css supports.
for e.x: `/fg red`, `/fg #ff0000`, `/fg rgb(255,0,0)` or anything that css's `color` property accepts.
but this changes the foreground color of all of the Nitab, including terminal.
You can also use the `clock` command to change position of the clock.
using `/clock center end` will have a result like this:
![idk3](https://user-images.githubusercontent.com/88832088/211541497-6385b322-02d4-4b7b-9b0a-8c133601c48e.png)
or you can use `/clock right end` that completely changes position of the clock, and changes the align to end like the previous command:
![idk4](https://user-images.githubusercontent.com/88832088/211541908-3d790fe9-ea8e-4693-bc58-3b881bb37630.png)
it has autocomplete, so you can play around with it. the default value is `/clock center center`.

if you want some further customization, follow these:
Nitab uses a css in js framework called styled-components. so the class names and selectors are a bit weird:
![image](https://user-images.githubusercontent.com/88832088/211542430-eda4b8e2-7d46-4ac8-ab2d-88d0b13d80a1.png)
for example, to select the `StyledClock-sc-q3cvyg-0` you would think about the selector `.StyledClock-sc-q3cvyg-0` to use in custom css. but that isn't guaranteed to work every time. I suggest that you use `[class*="StyledClock"]` selector. when you used this selector, you can use `align-items`, `position: absolute`, `top` and `left` to align and position the clock.
You can type custom css in `Advanced` tab of Nitab's side menu and see the live changes.
and you can search [mdn](https://developer.mozilla.org/en-US/) about that properties that i told you about.

**Comment by nimaaskarian** [comment]
I think all is good right? I think we're safe to close this.
You can make another issue or reopen this if you have any problems.
