### ISSUE TITLE
Where to enter commands ??

### ISSUE THREAD

**Issue by GrosBourrin** [nimaaskarian/nitab#6]
Where to enter commands?? nowhere to do it.
Firefox 98.0.2 x64 Windows 10 x64
here is my screenshot, no options in the addon page too, show me where enter commands please !
![firefox_6qTtJFUxXj](https://user-images.githubusercontent.com/40931468/160494125-6f92e8bd-bfc2-47a6-ae1c-9dabf35ce712.png)
o

**Comment by nimaaskarian** [comment]
Hi. Just type in and it'll focus on Nitab's Terminal! Nitab uses minimum GUI elements to provide that cool and minimal experience.  
Nice window customization btw :)

**Comment by GrosBourrin** [comment]
noticed and works ! thanks, that was not very explicit at first ! ty

**Comment by nimaaskarian** [comment]
> noticed and works ! thanks, that was not very explicit at first ! ty

َYou're welcome! and sorry for the obscurity... I just updated the about section in [AMO](https://addons.mozilla.org/en-US/firefox/addon/nitab/). I hope things are more clear now :)
